version: "3.9"

services:
  web:
    build: ./.docker
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      - ./dist:/var/www/vhosts/winter.test
      - ./.docker/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ${SSH_AUTH_SOCK}:/run/host-services/ssh-auth.sock
    depends_on:
      - mysql_server
    networks:
      - winter.test-network
    working_dir: /var/www/vhosts/winter.test
    expose:
      - "9000"

  mysql_server:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./.docker/mariadb:/docker-entrypoint-initdb.d
    networks:
      - winter.test-network
    expose:
      - "3306"

  nginx:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/logs:/var/log/nginx
      - ./dist:/var/www/vhosts/winter.test
    depends_on:
      - web
      - mysql_server
    networks:
      winter.test-network:
        aliases:
          - nginx
          - winter.test

networks:
  winter.test-network:
    driver: bridge

